// ============================================================
// GENERATE CUSTOMER BILLING PAGE - FIXED using string concatenation
// ============================================================

function generateCustomerBillingPage(organization) {
    var escapeHtml = function(str) {
        if (!str) return '';
        return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;').replace(/'/g, '&#039;');
    };

    var bizName = escapeHtml(organization.businessName || 'WiFi Business');
    var tagline = escapeHtml(organization.businessTagline || 'Fast • Secure • Reliable');
    var primaryColor = escapeHtml(organization.primaryColor || '#00c853');
    var secondaryColor = escapeHtml(organization.secondaryColor || '#00e676');
    var accentColor = escapeHtml(organization.accentColor || '#0f2027');
    var supportPhone = escapeHtml(organization.supportPhone || '0796587763');
    var supportEmail = escapeHtml(organization.supportEmail || 'support@example.com');
    var mpesaTill = escapeHtml(organization.mpesaTill || '');
    var orgId = escapeHtml(organization.id);
    var orgEmail = escapeHtml(organization.email || '');
    var plans = organization.plans || [];

    var plansHtml = '';
    for (var i = 0; i < plans.length; i++) {
        var p = plans[i];
        var duration = p.duration_seconds || 3600;
        var hours = Math.floor(duration / 3600);
        var days = Math.floor(duration / 86400);
        var durStr = '';
        if (days > 0) durStr = days + 'd';
        else if (hours > 0) durStr = hours + 'h';
        else durStr = Math.floor(duration / 60) + 'm';
        var isPopular = p.id === '1_Week_1_Device' || p.id === '24_Hours' || p.id === '8_Hours';
        
        plansHtml += '<div class="plan-card' + (i === 0 ? ' selected' : '') + '" data-id="' + escapeHtml(p.id) + '" data-price="' + p.price + '" onclick="selectPlan(this, \'' + escapeHtml(p.id) + '\', ' + p.price + ')">';
        if (isPopular) {
            plansHtml += '<div class="popular">🔥 Popular</div>';
        }
        plansHtml += '<div class="name">' + escapeHtml(p.name) + '</div>';
        plansHtml += '<div class="price">KES ' + p.price + ' <span>/ ' + durStr + '</span></div>';
        plansHtml += '<div class="features">';
        plansHtml += '<span>📱 ' + (p.devices || 1) + ' device' + (p.devices > 1 ? 's' : '') + '</span>';
        plansHtml += '<span>⏱ ' + durStr + '</span>';
        plansHtml += '</div>';
        plansHtml += '</div>';
    }

    if (!plansHtml) {
        plansHtml = '<div style="text-align:center;padding:20px;color:#666;grid-column:1/-1;">No plans available</div>';
    }

    var html = '<!DOCTYPE html>\n';
    html += '<html lang="en">\n';
    html += '<head>\n';
    html += '    <meta charset="UTF-8">\n';
    html += '    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
    html += '    <title>' + bizName + ' - WiFi</title>\n';
    html += '    <style>\n';
    html += '        * { margin: 0; padding: 0; box-sizing: border-box; }\n';
    html += '        body { font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, sans-serif; background: ' + accentColor + '; color: #ffffff; min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; }\n';
    html += '        .container { max-width: 520px; width: 100%; background: #121829; border-radius: 24px; padding: 32px 28px; border: 1px solid rgba(255,255,255,0.05); box-shadow: 0 20px 60px rgba(0,0,0,0.5); }\n';
    html += '        .brand { text-align: center; margin-bottom: 24px; }\n';
    html += '        .brand .logo { font-size: 48px; margin-bottom: 4px; }\n';
    html += '        .brand h1 { font-size: 26px; font-weight: 700; color: ' + primaryColor + '; }\n';
    html += '        .brand .tagline { color: #888; font-size: 14px; margin-top: 2px; }\n';
    html += '        .brand .badge { display: inline-block; background: rgba(0,200,83,0.12); color: ' + primaryColor + '; padding: 2px 16px; border-radius: 20px; font-size: 11px; font-weight: 600; margin-top: 4px; }\n';
    if (mpesaTill) {
        html += '        .brand .paybill { display: inline-block; background: rgba(255,193,7,0.12); color: #ffc107; padding: 2px 14px; border-radius: 20px; font-size: 11px; font-weight: 600; margin-top: 4px; margin-left: 6px; }\n';
    }
    html += '        .status-banner { padding: 10px 14px; border-radius: 10px; margin-bottom: 16px; text-align: center; font-size: 13px; display: none; }\n';
    html += '        .status-banner.show { display: block; }\n';
    html += '        .status-banner.success { background: rgba(0,200,83,0.1); border: 1px solid rgba(0,200,83,0.15); color: #00c853; }\n';
    html += '        .status-banner.warning { background: rgba(255,193,7,0.1); border: 1px solid rgba(255,193,7,0.15); color: #ffc107; }\n';
    html += '        .status-banner.error { background: rgba(255,68,68,0.1); border: 1px solid rgba(255,68,68,0.15); color: #ff4444; }\n';
    html += '        .status-banner.info { background: rgba(33,150,243,0.1); border: 1px solid rgba(33,150,243,0.15); color: #2196f3; }\n';
    html += '        .section-title { font-size: 16px; font-weight: 600; margin: 20px 0 12px 0; color: #fff; display: flex; align-items: center; gap: 8px; }\n';
    html += '        .plan-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }\n';
    html += '        .plan-card { background: rgba(255,255,255,0.03); border-radius: 12px; padding: 14px 12px; border: 2px solid rgba(255,255,255,0.05); cursor: pointer; transition: all 0.25s ease; text-align: center; position: relative; }\n';
    html += '        .plan-card:hover { background: rgba(255,255,255,0.06); border-color: ' + primaryColor + '40; transform: translateY(-2px); }\n';
    html += '        .plan-card.selected { border-color: ' + primaryColor + '; background: ' + primaryColor + '15; box-shadow: 0 0 20px ' + primaryColor + '20; }\n';
    html += '        .plan-card .name { font-weight: 600; font-size: 14px; color: #fff; }\n';
    html += '        .plan-card .price { font-size: 20px; font-weight: 700; color: ' + primaryColor + '; margin: 2px 0; }\n';
    html += '        .plan-card .price span { font-size: 12px; font-weight: 400; color: #666; }\n';
    html += '        .plan-card .features { font-size: 11px; color: #666; margin-top: 4px; }\n';
    html += '        .plan-card .features span { display: inline-block; background: rgba(255,255,255,0.04); padding: 1px 10px; border-radius: 12px; margin: 2px 2px; }\n';
    html += '        .plan-card .popular { position: absolute; top: -8px; right: -8px; background: #ff6b35; color: #fff; font-size: 9px; font-weight: 700; padding: 2px 10px; border-radius: 20px; text-transform: uppercase; letter-spacing: 0.5px; }\n';
    html += '        .input-group { margin: 14px 0 12px 0; }\n';
    html += '        .input-group label { display: block; color: #aaa; font-size: 13px; font-weight: 500; margin-bottom: 4px; }\n';
    html += '        .input-group input { width: 100%; padding: 12px 16px; background: #0a0e17; border: 2px solid rgba(255,255,255,0.06); border-radius: 10px; color: #fff; font-size: 16px; outline: none; transition: 0.25s; }\n';
    html += '        .input-group input:focus { border-color: ' + primaryColor + '; box-shadow: 0 0 0 3px ' + primaryColor + '20; }\n';
    html += '        .input-group input::placeholder { color: #444; }\n';
    html += '        .btn { width: 100%; padding: 13px; background: ' + primaryColor + '; border: none; border-radius: 10px; font-size: 16px; font-weight: 700; color: #000; cursor: pointer; transition: all 0.25s ease; font-family: inherit; display: flex; align-items: center; justify-content: center; gap: 8px; }\n';
    html += '        .btn:hover { background: ' + secondaryColor + '; transform: scale(1.01); }\n';
    html += '        .btn:disabled { opacity: 0.5; cursor: not-allowed; transform: none; }\n';
    html += '        .btn-secondary { background: rgba(255,255,255,0.06); color: #fff; }\n';
    html += '        .btn-secondary:hover { background: rgba(255,255,255,0.1); }\n';
    html += '        .btn .spinner { display: inline-block; width: 18px; height: 18px; border: 2px solid rgba(0,0,0,0.1); border-top-color: #000; border-radius: 50%; animation: spin 0.8s linear infinite; }\n';
    html += '        @keyframes spin { to { transform: rotate(360deg); } }\n';
    html += '        .divider { display: flex; align-items: center; gap: 16px; margin: 16px 0; color: #444; font-size: 12px; }\n';
    html += '        .divider::before, .divider::after { content: \'\'; flex: 1; height: 1px; background: rgba(255,255,255,0.04); }\n';
    html += '        .voucher-row { display: flex; gap: 10px; }\n';
    html += '        .voucher-row input { flex: 1; padding: 11px 14px; background: #0a0e17; border: 2px solid rgba(255,255,255,0.06); border-radius: 10px; color: #fff; font-size: 14px; outline: none; }\n';
    html += '        .voucher-row input:focus { border-color: ' + primaryColor + '; }\n';
    html += '        .voucher-row .btn { flex: 0 0 auto; width: auto; padding: 11px 20px; font-size: 13px; }\n';
    html += '        .result-box { margin-top: 10px; padding: 10px 14px; border-radius: 10px; font-size: 13px; display: none; }\n';
    html += '        .result-box.show { display: block; }\n';
    html += '        .result-box.success { background: rgba(0,200,83,0.08); color: #00c853; border: 1px solid rgba(0,200,83,0.1); }\n';
    html += '        .result-box.error { background: rgba(255,68,68,0.08); color: #ff4444; border: 1px solid rgba(255,68,68,0.1); }\n';
    html += '        .result-box.info { background: rgba(33,150,243,0.08); color: #2196f3; border: 1px solid rgba(33,150,243,0.1); }\n';
    html += '        .check-row { display: flex; gap: 10px; margin-top: 14px; }\n';
    html += '        .check-row input { flex: 1; padding: 11px 14px; background: #0a0e17; border: 2px solid rgba(255,255,255,0.06); border-radius: 10px; color: #fff; font-size: 14px; outline: none; }\n';
    html += '        .check-row input:focus { border-color: ' + primaryColor + '; }\n';
    html += '        .check-row .btn { flex: 0 0 auto; width: auto; padding: 11px 20px; font-size: 13px; }\n';
    html += '        .upgrade-section { margin-top: 16px; padding: 16px; background: rgba(255,193,7,0.05); border-radius: 12px; border: 1px solid rgba(255,193,7,0.1); display: none; }\n';
    html += '        .upgrade-section.show { display: block; }\n';
    html += '        .upgrade-section h3 { color: #ffc107; font-size: 16px; margin-bottom: 4px; }\n';
    html += '        .upgrade-section p { color: #888; font-size: 13px; margin-bottom: 10px; }\n';
    html += '        .upgrade-section .plan-options { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 8px; }\n';
    html += '        .upgrade-section .plan-options .btn { padding: 10px; font-size: 12px; background: rgba(255,255,255,0.05); color: #fff; }\n';
    html += '        .upgrade-section .plan-options .btn:hover { background: rgba(255,255,255,0.1); }\n';
    html += '        .connected-overlay { position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: ' + accentColor + '; display: none; flex-direction: column; align-items: center; justify-content: center; z-index: 9999; padding: 30px; }\n';
    html += '        .connected-overlay.active { display: flex; }\n';
    html += '        .connected-overlay .icon { font-size: 72px; margin-bottom: 12px; }\n';
    html += '        .connected-overlay .title { font-size: 28px; font-weight: 700; color: ' + primaryColor + '; }\n';
    html += '        .connected-overlay .sub { color: #888; font-size: 16px; margin-top: 4px; }\n';
    html += '        .connected-overlay .timer-box { background: rgba(255,255,255,0.03); padding: 20px 40px; border-radius: 16px; border: 1px solid rgba(255,255,255,0.04); margin: 16px 0; text-align: center; }\n';
    html += '        .connected-overlay .timer-box .label { color: #666; font-size: 12px; text-transform: uppercase; letter-spacing: 2px; }\n';
    html += '        .connected-overlay .timer-box .time { font-size: 44px; font-weight: 700; color: ' + primaryColor + '; font-family: \'Courier New\', monospace; letter-spacing: 4px; }\n';
    html += '        .connected-overlay .timer-box .time.expired { color: #ff4444; }\n';
    html += '        .connected-overlay .creds { background: rgba(255,255,255,0.03); border-radius: 12px; padding: 14px 24px; border: 1px solid rgba(255,255,255,0.04); width: 100%; max-width: 360px; margin: 8px 0; }\n';
    html += '        .connected-overlay .creds .row { display: flex; justify-content: space-between; padding: 4px 0; border-bottom: 1px solid rgba(255,255,255,0.03); font-size: 13px; }\n';
    html += '        .connected-overlay .creds .row:last-child { border-bottom: none; }\n';
    html += '        .connected-overlay .creds .label { color: #666; }\n';
    html += '        .connected-overlay .creds .value { color: #fff; font-family: monospace; }\n';
    html += '        .connected-overlay .enjoy { color: ' + primaryColor + '; font-size: 18px; margin-top: 12px; opacity: 0.9; }\n';
    html += '        .connected-overlay .powered { color: #444; font-size: 12px; margin-top: 24px; }\n';
    html += '        .connected-overlay .powered .brand { color: ' + primaryColor + '; font-weight: 600; }\n';
    html += '        .toast { position: fixed; bottom: 30px; left: 50%; transform: translateX(-50%); background: #121829; padding: 12px 24px; border-radius: 12px; border: 1px solid rgba(255,255,255,0.06); color: #fff; font-size: 14px; z-index: 999; max-width: 90%; text-align: center; box-shadow: 0 20px 60px rgba(0,0,0,0.5); display: none; animation: toastIn 0.35s ease; }\n';
    html += '        .toast.show { display: block; }\n';
    html += '        .toast.success { border-color: ' + primaryColor + '; }\n';
    html += '        .toast.error { border-color: #ff4444; }\n';
    html += '        .toast.info { border-color: #2196f3; }\n';
    html += '        @keyframes toastIn { from { opacity: 0; transform: translateX(-50%) translateY(30px); } to { opacity: 1; transform: translateX(-50%) translateY(0); } }\n';
    html += '        @media (max-width: 480px) { .container { padding: 20px 16px; } .plan-grid { grid-template-columns: 1fr 1fr; gap: 8px; } .plan-card { padding: 12px 10px; } .plan-card .price { font-size: 18px; } .voucher-row { flex-direction: column; } .voucher-row .btn { width: 100%; } .check-row { flex-direction: column; } .check-row .btn { width: 100%; } .connected-overlay .timer-box .time { font-size: 34px; } .connected-overlay .timer-box { padding: 20px; } .upgrade-section .plan-options { grid-template-columns: 1fr 1fr; } }\n';
    html += '        @media (max-width: 380px) { .plan-grid { grid-template-columns: 1fr; } .upgrade-section .plan-options { grid-template-columns: 1fr; } }\n';
    html += '    </style>\n';
    html += '</head>\n';
    html += '<body>\n';

    // Main container
    html += '<div class="container" id="app">\n';
    html += '    <div class="brand">\n';
    html += '        <div class="logo">🌐</div>\n';
    html += '        <h1>' + bizName + '</h1>\n';
    html += '        <p class="tagline">' + tagline + '</p>\n';
    html += '        <div>\n';
    html += '            <span class="badge">🔐 Secure</span>\n';
    if (mpesaTill) {
        html += '            <span class="paybill">💰 Paybill: ' + mpesaTill + '</span>\n';
    }
    html += '        </div>\n';
    html += '    </div>\n';

    html += '    <div class="status-banner" id="statusBanner"></div>\n';

    html += '    <div class="section-title">📶 Choose Your Plan</div>\n';
    html += '    <div class="plan-grid" id="planGrid">\n';
    html += plansHtml;
    html += '    </div>\n';

    html += '    <div class="input-group">\n';
    html += '        <label>📱 M-Pesa Phone Number</label>\n';
    html += '        <input type="tel" id="phoneInput" placeholder="0712345678" />\n';
    html += '    </div>\n';

    html += '    <button class="btn" id="payBtn" onclick="initiatePayment()" disabled>💳 Select a plan to pay</button>\n';
    html += '    <div id="paymentResult" class="result-box"></div>\n';

    html += '    <div class="divider">or use a voucher</div>\n';
    html += '    <div class="voucher-row">\n';
    html += '        <input type="text" id="voucherInput" placeholder="🎟️ Enter voucher code" />\n';
    html += '        <button class="btn btn-secondary" onclick="redeemVoucher()">Redeem</button>\n';
    html += '    </div>\n';
    html += '    <div id="voucherResult" class="result-box"></div>\n';

    html += '    <div class="check-row">\n';
    html += '        <input type="tel" id="checkPhoneInput" placeholder="🔍 Check your plan" />\n';
    html += '        <button class="btn btn-secondary" onclick="checkPlan()">Check</button>\n';
    html += '    </div>\n';
    html += '    <div id="checkResult" class="result-box"></div>\n';

    html += '    <div class="upgrade-section" id="upgradeSection">\n';
    html += '        <h3>⛔ Your subscription has expired</h3>\n';
    html += '        <p>Subscribe to continue using the service. Pay monthly via M-Pesa.</p>\n';
    html += '        <div class="plan-options">\n';
    html += '            <button class="btn" onclick="subscribeToPlan(\'starter\')">🌱 Starter<br><small>KSh 500</small></button>\n';
    html += '            <button class="btn" onclick="subscribeToPlan(\'pro\')">🚀 Pro<br><small>KSh 1,000</small></button>\n';
    html += '            <button class="btn" onclick="subscribeToPlan(\'business\')">💼 Business<br><small>KSh 2,000</small></button>\n';
    html += '        </div>\n';
    html += '        <div id="subscribeResult" style="margin-top:8px;font-size:13px;text-align:center;"></div>\n';
    html += '    </div>\n';

    html += '    <div style="text-align:center;color:#444;font-size:11px;margin-top:18px;border-top:1px solid rgba(255,255,255,0.03);padding-top:14px;">\n';
    html += '        Powered by <span style="color:' + primaryColor + ';font-weight:600;">GICH WiFi</span> · Secure · Fast · Reliable\n';
    html += '        <br><span id="supportInfo" style="color:#555;font-size:11px;">📞 ' + supportPhone + (supportEmail ? ' · ✉️ ' + supportEmail : '') + '</span>\n';
    html += '    </div>\n';
    html += '</div>\n';

    // Connected overlay
    html += '<div class="connected-overlay" id="connectedOverlay">\n';
    html += '    <div class="icon">🎉</div>\n';
    html += '    <div class="title" id="connTitle">You\'re Connected!</div>\n';
    html += '    <div class="sub" id="connSub">Enjoy your high-speed internet</div>\n';
    html += '    <div class="timer-box">\n';
    html += '        <div class="label">⏱ Time Remaining</div>\n';
    html += '        <div class="time" id="connTimer">--:--:--</div>\n';
    html += '    </div>\n';
    html += '    <div class="creds">\n';
    html += '        <div class="row"><span class="label">Username</span><span class="value" id="connUser">-</span></div>\n';
    html += '        <div class="row"><span class="label">Password</span><span class="value" id="connPass">-</span></div>\n';
    html += '        <div class="row"><span class="label">Plan</span><span class="value" id="connPlan">-</span></div>\n';
    html += '    </div>\n';
    html += '    <div class="enjoy" id="connEnjoy">🌐 Enjoy your browsing!</div>\n';
    html += '    <div class="powered">Powered by <span class="brand">GICH WiFi</span></div>\n';
    html += '</div>\n';

    // Toast
    html += '<div class="toast" id="toast">\n';
    html += '    <span id="toastIcon">✅</span>\n';
    html += '    <span id="toastMessage">Success!</span>\n';
    html += '</div>\n';

    // JavaScript - Using a completely different approach - no variable references
    html += '<script>\n';
    html += '    (function() {\n';
    html += '        var ORG_ID = "' + orgId + '";\n';
    html += '        var ORG_EMAIL = "' + orgEmail + '";\n';
    html += '        var API_URL = "' + (process.env.RENDER_URL || 'https://billing-system-fm9a.onrender.com') + '/api";\n';
    html += '        var selectedPlan = null;\n';
    html += '        var selectedPlanPrice = 0;\n';
    html += '        var credentials = null;\n';
    html += '        var countdownInterval = null;\n';
    html += '        var pollingInterval = null;\n';
    html += '        var subscriptionStatus = null;\n';
    html += '\n';
    html += '        function getEl(id) { return document.getElementById(id); }\n';
    html += '\n';
    html += '        function selectPlan(el, id, price) {\n';
    html += '            var cards = document.querySelectorAll(".plan-card");\n';
    html += '            for (var i = 0; i < cards.length; i++) { cards[i].classList.remove("selected"); }\n';
    html += '            el.classList.add("selected");\n';
    html += '            selectedPlan = id;\n';
    html += '            selectedPlanPrice = price;\n';
    html += '            getEl("payBtn").textContent = "💳 Pay KSh " + price;\n';
    html += '            getEl("payBtn").disabled = false;\n';
    html += '            getEl("paymentResult").className = "result-box";\n';
    html += '            getEl("paymentResult").textContent = "";\n';
    html += '        }\n';
    html += '\n';
    html += '        var firstPlan = document.querySelector(".plan-card");\n';
    html += '        if (firstPlan) {\n';
    html += '            var price = parseInt(firstPlan.dataset.price) || 0;\n';
    html += '            getEl("payBtn").textContent = "💳 Pay KSh " + price;\n';
    html += '            getEl("payBtn").disabled = false;\n';
    html += '            selectedPlan = firstPlan.dataset.id;\n';
    html += '            selectedPlanPrice = price;\n';
    html += '        }\n';
    html += '\n';
    html += '        function checkSubscriptionStatus() {\n';
    html += '            if (!ORG_EMAIL) return;\n';
    html += '            fetch(API_URL + "/client/subscription-status?email=" + encodeURIComponent(ORG_EMAIL))\n';
    html += '                .then(function(r) { return r.json(); })\n';
    html += '                .then(function(data) {\n';
    html += '                    if (data.success) {\n';
    html += '                        subscriptionStatus = data.status;\n';
    html += '                        updateStatusBanner(subscriptionStatus);\n';
    html += '                        var upgradeSection = getEl("upgradeSection");\n';
    html += '                        if (subscriptionStatus.status === "expired" || subscriptionStatus.status === "no_subscription") {\n';
    html += '                            upgradeSection.classList.add("show");\n';
    html += '                        } else {\n';
    html += '                            upgradeSection.classList.remove("show");\n';
    html += '                        }\n';
    html += '                    }\n';
    html += '                })\n';
    html += '                .catch(function(err) { console.error("Error checking subscription:", err); });\n';
    html += '        }\n';
    html += '\n';
    html += '        function updateStatusBanner(status) {\n';
    html += '            var banner = getEl("statusBanner");\n';
    html += '            if (!status || status.status === "active") {\n';
    html += '                banner.className = "status-banner";\n';
    html += '                banner.textContent = "";\n';
    html += '                return;\n';
    html += '            }\n';
    html += '            if (status.status === "trial") {\n';
    html += '                banner.className = "status-banner show info";\n';
    html += '                banner.textContent = "🎁 Free Trial: " + status.daysLeft + " days remaining";\n';
    html += '                return;\n';
    html += '            }\n';
    html += '            if (status.status === "expired" || status.status === "no_subscription") {\n';
    html += '                banner.className = "status-banner show error";\n';
    html += '                banner.textContent = "⛔ " + (status.message || "No active subscription. Please subscribe below.");\n';
    html += '                return;\n';
    html += '            }\n';
    html += '            banner.className = "status-banner show warning";\n';
    html += '            banner.textContent = status.message || "Subscription status unknown";\n';
    html += '        }\n';
    html += '\n';
    html += '        function initiatePayment() {\n';
    html += '            var phone = getEl("phoneInput").value.trim();\n';
    html += '            var resultEl = getEl("paymentResult");\n';
    html += '            if (!phone || phone.length < 10) {\n';
    html += '                resultEl.className = "result-box show error";\n';
    html += '                resultEl.textContent = "📱 Please enter a valid phone number";\n';
    html += '                return;\n';
    html += '            }\n';
    html += '            if (!selectedPlan) {\n';
    html += '                resultEl.className = "result-box show error";\n';
    html += '                resultEl.textContent = "Please select a plan first";\n';
    html += '                return;\n';
    html += '            }\n';
    html += '            var btn = getEl("payBtn");\n';
    html += '            btn.disabled = true;\n';
    html += '            btn.innerHTML = "<span class=\\"spinner\\"></span> Processing...";\n';
    html += '            resultEl.className = "result-box show info";\n';
    html += '            resultEl.textContent = "⏳ Sending M-Pesa request...";\n';
    html += '            fetch(API_URL + "/payment/initiate", {\n';
    html += '                method: "POST",\n';
    html += '                headers: { "Content-Type": "application/json" },\n';
    html += '                body: JSON.stringify({\n';
    html += '                    phoneNumber: phone,\n';
    html += '                    amount: selectedPlanPrice,\n';
    html += '                    planId: selectedPlan,\n';
    html += '                    organizationId: ORG_ID\n';
    html += '                })\n';
    html += '            })\n';
    html += '            .then(function(r) { return r.json(); })\n';
    html += '            .then(function(data) {\n';
    html += '                if (data.success) {\n';
    html += '                    resultEl.className = "result-box show success";\n';
    html += '                    resultEl.textContent = "✅ M-Pesa prompt sent! Check your phone.";\n';
    html += '                    showToast("📱 M-Pesa prompt sent!", "success");\n';
    html += '                    if (data.isFree) {\n';
    html += '                        setTimeout(function() { fetchCredentials(data.transactionId); }, 1000);\n';
    html += '                    } else {\n';
    html += '                        startPolling(data.transactionId);\n';
    html += '                    }\n';
    html += '                } else {\n';
    html += '                    resultEl.className = "result-box show error";\n';
    html += '                    resultEl.textContent = "❌ " + (data.message || "Payment failed");\n';
    html += '                    showToast("❌ Payment failed", "error");\n';
    html += '                    btn.disabled = false;\n';
    html += '                    btn.innerHTML = "💳 Pay KSh " + selectedPlanPrice;\n';
    html += '                }\n';
    html += '            })\n';
    html += '            .catch(function(err) {\n';
    html += '                console.error("Payment error:", err);\n';
    html += '                resultEl.className = "result-box show error";\n';
    html += '                resultEl.textContent = "❌ Network error: " + err.message;\n';
    html += '                showToast("❌ Network error", "error");\n';
    html += '                btn.disabled = false;\n';
    html += '                btn.innerHTML = "💳 Pay KSh " + selectedPlanPrice;\n';
    html += '            });\n';
    html += '        }\n';
    html += '\n';
    html += '        function startPolling(transactionId) {\n';
    html += '            var attempts = 0;\n';
    html += '            var maxAttempts = 30;\n';
    html += '            if (pollingInterval) clearInterval(pollingInterval);\n';
    html += '            pollingInterval = setInterval(function() {\n';
    html += '                attempts++;\n';
    html += '                if (attempts > maxAttempts) {\n';
    html += '                    clearInterval(pollingInterval);\n';
    html += '                    pollingInterval = null;\n';
    html += '                    showToast("⏱️ Payment timed out", "error");\n';
    html += '                    getEl("payBtn").disabled = false;\n';
    html += '                    getEl("payBtn").innerHTML = "💳 Pay KSh " + selectedPlanPrice;\n';
    html += '                    return;\n';
    html += '                }\n';
    html += '                fetch(API_URL + "/transaction/" + transactionId)\n';
    html += '                    .then(function(r) { return r.json(); })\n';
    html += '                    .then(function(data) {\n';
    html += '                        if (data.success) {\n';
    html += '                            var tx = data.data;\n';
    html += '                            if (tx.status === "completed") {\n';
    html += '                                clearInterval(pollingInterval);\n';
    html += '                                pollingInterval = null;\n';
    html += '                                showToast("✅ Payment successful!", "success");\n';
    html += '                                getEl("paymentResult").className = "result-box show success";\n';
    html += '                                getEl("paymentResult").textContent = "✅ Payment successful! Connecting...";\n';
    html += '                                fetchCredentials(transactionId);\n';
    html += '                            } else if (tx.status === "cancelled" || tx.status === "failed") {\n';
    html += '                                clearInterval(pollingInterval);\n';
    html += '                                pollingInterval = null;\n';
    html += '                                showToast("❌ Payment " + tx.status, "error");\n';
    html += '                                getEl("paymentResult").className = "result-box show error";\n';
    html += '                                getEl("paymentResult").textContent = "❌ Payment " + tx.status;\n';
    html += '                                getEl("payBtn").disabled = false;\n';
    html += '                                getEl("payBtn").innerHTML = "💳 Pay KSh " + selectedPlanPrice;\n';
    html += '                            }\n';
    html += '                        }\n';
    html += '                    })\n';
    html += '                    .catch(function(err) { console.error("Polling error:", err); });\n';
    html += '            }, 3000);\n';
    html += '        }\n';
    html += '\n';
    html += '        function fetchCredentials(transactionId) {\n';
    html += '            fetch(API_URL + "/get-credentials/" + transactionId)\n';
    html += '                .then(function(r) { return r.json(); })\n';
    html += '                .then(function(data) {\n';
    html += '                    if (data.success) {\n';
    html += '                        credentials = {\n';
    html += '                            username: data.username || "N/A",\n';
    html += '                            password: data.password || "N/A",\n';
    html += '                            plan: data.plan || "N/A",\n';
    html += '                            expiresAt: data.expiresAt\n';
    html += '                        };\n';
    html += '                        showConnectedPage(credentials);\n';
    html += '                    } else {\n';
    html += '                        showToast("❌ Failed to get credentials", "error");\n';
    html += '                    }\n';
    html += '                })\n';
    html += '                .catch(function(err) {\n';
    html += '                    console.error("Error fetching credentials:", err);\n';
    html += '                    showToast("❌ Error fetching credentials", "error");\n';
    html += '                });\n';
    html += '        }\n';
    html += '\n';
    html += '        function showConnectedPage(cred) {\n';
    html += '            document.getElementById("app").style.display = "none";\n';
    html += '            var overlay = getEl("connectedOverlay");\n';
    html += '            overlay.classList.add("active");\n';
    html += '            getEl("connUser").textContent = cred.username || "N/A";\n';
    html += '            getEl("connPass").textContent = cred.password || "N/A";\n';
    html += '            getEl("connPlan").textContent = cred.plan || "N/A";\n';
    html += '            if (cred.expiresAt) { startCountdown(cred.expiresAt); }\n';
    html += '        }\n';
    html += '\n';
    html += '        function startCountdown(expiresAt) {\n';
    html += '            if (countdownInterval) clearInterval(countdownInterval);\n';
    html += '            var timer = getEl("connTimer");\n';
    html += '            function update() {\n';
    html += '                var now = Date.now();\n';
    html += '                var expiry = new Date(expiresAt).getTime();\n';
    html += '                var diff = Math.max(0, expiry - now);\n';
    html += '                if (diff <= 0) {\n';
    html += '                    timer.textContent = "00:00:00";\n';
    html += '                    timer.classList.add("expired");\n';
    html += '                    getEl("connEnjoy").textContent = "⏰ Your plan has expired. Please reconnect.";\n';
    html += '                    clearInterval(countdownInterval);\n';
    html += '                    return;\n';
    html += '                }\n';
    html += '                timer.classList.remove("expired");\n';
    html += '                var hours = Math.floor(diff / 3600000);\n';
    html += '                var mins = Math.floor((diff % 3600000) / 60000);\n';
    html += '                var secs = Math.floor((diff % 60000) / 1000);\n';
    html += '                timer.textContent = String(hours).padStart(2, "0") + ":" + String(mins).padStart(2, "0") + ":" + String(secs).padStart(2, "0");\n';
    html += '            }\n';
    html += '            update();\n';
    html += '            countdownInterval = setInterval(update, 1000);\n';
    html += '        }\n';
    html += '\n';
    html += '        function redeemVoucher() {\n';
    html += '            var code = getEl("voucherInput").value.trim().toUpperCase();\n';
    html += '            var resultEl = getEl("voucherResult");\n';
    html += '            if (!code) {\n';
    html += '                resultEl.className = "result-box show error";\n';
    html += '                resultEl.textContent = "❌ Please enter a voucher code";\n';
    html += '                return;\n';
    html += '            }\n';
    html += '            resultEl.className = "result-box show info";\n';
    html += '            resultEl.textContent = "⏳ Redeeming...";\n';
    html += '            fetch(API_URL + "/voucher/redeem", {\n';
    html += '                method: "POST",\n';
    html += '                headers: { "Content-Type": "application/json" },\n';
    html += '                body: JSON.stringify({ code: code, phoneNumber: getEl("phoneInput").value.trim() || "voucher_user" })\n';
    html += '            })\n';
    html += '            .then(function(r) { return r.json(); })\n';
    html += '            .then(function(data) {\n';
    html += '                if (data.success) {\n';
    html += '                    resultEl.className = "result-box show success";\n';
    html += '                    resultEl.textContent = "✅ Voucher redeemed! Connecting...";\n';
    html += '                    showToast("🎟️ Voucher redeemed!", "success");\n';
    html += '                    credentials = {\n';
    html += '                        username: data.data.username || "voucher_user",\n';
    html += '                        password: data.data.password || "pass_" + Date.now(),\n';
    html += '                        plan: data.data.planName || "Voucher Plan",\n';
    html += '                        expiresAt: data.data.expiresAt || new Date(Date.now() + 3600000).toISOString()\n';
    html += '                    };\n';
    html += '                    showConnectedPage(credentials);\n';
    html += '                } else {\n';
    html += '                    resultEl.className = "result-box show error";\n';
    html += '                    resultEl.textContent = "❌ " + (data.message || "Invalid voucher");\n';
    html += '                    showToast("❌ Invalid voucher", "error");\n';
    html += '                }\n';
    html += '            })\n';
    html += '            .catch(function(err) {\n';
    html += '                console.error("Voucher error:", err);\n';
    html += '                resultEl.className = "result-box show error";\n';
    html += '                resultEl.textContent = "❌ Network error";\n';
    html += '            });\n';
    html += '        }\n';
    html += '\n';
    html += '        function checkPlan() {\n';
    html += '            var phone = getEl("checkPhoneInput").value.trim();\n';
    html += '            var resultEl = getEl("checkResult");\n';
    html += '            if (!phone || phone.length < 10) {\n';
    html += '                resultEl.className = "result-box show error";\n';
    html += '                resultEl.textContent = "❌ Please enter a valid phone number";\n';
    html += '                return;\n';
    html += '            }\n';
    html += '            resultEl.className = "result-box show info";\n';
    html += '            resultEl.textContent = "⏳ Checking...";\n';
    html += '            fetch(API_URL + "/check-active?phone=" + encodeURIComponent(phone))\n';
    html += '                .then(function(r) { return r.json(); })\n';
    html += '                .then(function(data) {\n';
    html += '                    if (data.success && data.active) {\n';
    html += '                        resultEl.className = "result-box show success";\n';
    html += '                        resultEl.textContent = "✅ Active plan found! Connecting...";\n';
    html += '                        credentials = {\n';
    html += '                            username: data.data.username,\n';
    html += '                            password: data.data.password,\n';
    html += '                            plan: data.data.planName,\n';
    html += '                            expiresAt: data.data.expiresAt\n';
    html += '                        };\n';
    html += '                        showConnectedPage(credentials);\n';
    html += '                    } else {\n';
    html += '                        resultEl.className = "result-box show error";\n';
    html += '                        resultEl.textContent = "❌ No active plan found for this number.";\n';
    html += '                    }\n';
    html += '                })\n';
    html += '                .catch(function(err) {\n';
    html += '                    console.error("Check plan error:", err);\n';
    html += '                    resultEl.className = "result-box show error";\n';
    html += '                    resultEl.textContent = "❌ Network error";\n';
    html += '                });\n';
    html += '        }\n';
    html += '\n';
    html += '        function subscribeToPlan(planType) {\n';
    html += '            var phone = getEl("phoneInput").value.trim();\n';
    html += '            if (!phone || phone.length < 10) {\n';
    html += '                showToast("📱 Please enter your phone number to pay", "error");\n';
    html += '                getEl("phoneInput").focus();\n';
    html += '                return;\n';
    html += '            }\n';
    html += '            var prices = { starter: 500, pro: 1000, business: 2000 };\n';
    html += '            var amount = prices[planType] || 500;\n';
    html += '            var btn = document.querySelector(".upgrade-section .plan-options .btn");\n';
    html += '            if (btn) { btn.disabled = true; btn.innerHTML = "<span class=\\"spinner\\"></span>"; }\n';
    html += '            var resultEl = getEl("subscribeResult");\n';
    html += '            resultEl.textContent = "⏳ Processing subscription payment...";\n';
    html += '            resultEl.style.color = "#aaa";\n';
    html += '            fetch(API_URL + "/payment/initiate", {\n';
    html += '                method: "POST",\n';
    html += '                headers: { "Content-Type": "application/json" },\n';
    html += '                body: JSON.stringify({\n';
    html += '                    phoneNumber: phone,\n';
    html += '                    amount: amount,\n';
    html += '                    planId: "subscription_' + planType + '",\n';
    html += '                    organizationId: ORG_ID,\n';
    html += '                    isSubscription: true,\n';
    html += '                    subscriptionPlan: planType\n';
    html += '                })\n';
    html += '            })\n';
    html += '            .then(function(r) { return r.json(); })\n';
    html += '            .then(function(data) {\n';
    html += '                if (data.success) {\n';
    html += '                    resultEl.textContent = "✅ M-Pesa prompt sent! Check your phone.";\n';
    html += '                    resultEl.style.color = "#00c853";\n';
    html += '                    showToast("📱 M-Pesa prompt sent!", "success");\n';
    html += '                    pollSubscriptionPayment(data.transactionId, planType);\n';
    html += '                } else {\n';
    html += '                    resultEl.textContent = "❌ " + (data.message || "Payment failed");\n';
    html += '                    resultEl.style.color = "#ff4444";\n';
    html += '                    showToast("❌ Payment failed", "error");\n';
    html += '                    if (btn) { btn.disabled = false; btn.innerHTML = planType.charAt(0).toUpperCase() + planType.slice(1) + "<br><small>KSh " + amount + "</small>"; }\n';
    html += '                }\n';
    html += '            })\n';
    html += '            .catch(function(err) {\n';
    html += '                console.error("Subscription payment error:", err);\n';
    html += '                resultEl.textContent = "❌ Network error";\n';
    html += '                resultEl.style.color = "#ff4444";\n';
    html += '                showToast("❌ Network error", "error");\n';
    html += '                if (btn) { btn.disabled = false; btn.innerHTML = planType.charAt(0).toUpperCase() + planType.slice(1) + "<br><small>KSh " + amount + "</small>"; }\n';
    html += '            });\n';
    html += '        }\n';
    html += '\n';
    html += '        function pollSubscriptionPayment(transactionId, planType) {\n';
    html += '            var attempts = 0;\n';
    html += '            var maxAttempts = 30;\n';
    html += '            var interval = setInterval(function() {\n';
    html += '                attempts++;\n';
    html += '                if (attempts > maxAttempts) {\n';
    html += '                    clearInterval(interval);\n';
    html += '                    showToast("⏱️ Payment confirmation timed out.", "error");\n';
    html += '                    getEl("subscribeResult").textContent = "⏱️ Payment confirmation timed out.";\n';
    html += '                    getEl("subscribeResult").style.color = "#ff4444";\n';
    html += '                    return;\n';
    html += '                }\n';
    html += '                fetch(API_URL + "/transaction/" + transactionId)\n';
    html += '                    .then(function(r) { return r.json(); })\n';
    html += '                    .then(function(data) {\n';
    html += '                        if (data.success) {\n';
    html += '                            var tx = data.data;\n';
    html += '                            if (tx.status === "completed") {\n';
    html += '                                clearInterval(interval);\n';
    html += '                                showToast("✅ Subscription payment successful!", "success");\n';
    html += '                                getEl("subscribeResult").textContent = "✅ Payment successful! Activating subscription...";\n';
    html += '                                getEl("subscribeResult").style.color = "#00c853";\n';
    html += '                                activateSubscription(planType);\n';
    html += '                            } else if (tx.status === "cancelled" || tx.status === "failed") {\n';
    html += '                                clearInterval(interval);\n';
    html += '                                showToast("❌ Payment " + tx.status, "error");\n';
    html += '                                getEl("subscribeResult").textContent = "❌ Payment " + tx.status;\n';
    html += '                                getEl("subscribeResult").style.color = "#ff4444";\n';
    html += '                                var btns = document.querySelectorAll(".upgrade-section .plan-options .btn");\n';
    html += '                                for (var i = 0; i < btns.length; i++) {\n';
    html += '                                    btns[i].disabled = false;\n';
    html += '                                    btns[i].innerHTML = btns[i].textContent || "Subscribe";\n';
    html += '                                }\n';
    html += '                            }\n';
    html += '                        }\n';
    html += '                    })\n';
    html += '                    .catch(function(err) { console.error("Polling error:", err); });\n';
    html += '            }, 3000);\n';
    html += '        }\n';
    html += '\n';
    html += '        function activateSubscription(planType) {\n';
    html += '            fetch(API_URL + "/client/subscribe", {\n';
    html += '                method: "POST",\n';
    html += '                headers: { "Content-Type": "application/json" },\n';
    html += '                body: JSON.stringify({\n';
    html += '                    clientId: ORG_ID,\n';
    html += '                    plan: planType\n';
    html += '                })\n';
    html += '            })\n';
    html += '            .then(function(r) { return r.json(); })\n';
    html += '            .then(function(data) {\n';
    html += '                if (data.success) {\n';
    html += '                    showToast("✅ Subscription activated!", "success");\n';
    html += '                    getEl("subscribeResult").textContent = "✅ " + data.message;\n';
    html += '                    getEl("subscribeResult").style.color = "#00c853";\n';
    html += '                    getEl("upgradeSection").classList.remove("show");\n';
    html += '                    checkSubscriptionStatus();\n';
    html += '                    var btns = document.querySelectorAll(".upgrade-section .plan-options .btn");\n';
    html += '                    for (var i = 0; i < btns.length; i++) {\n';
    html += '                        btns[i].disabled = false;\n';
    html += '                        btns[i].innerHTML = btns[i].textContent || "Subscribe";\n';
    html += '                    }\n';
    html += '                } else {\n';
    html += '                    showToast("❌ Failed to activate subscription", "error");\n';
    html += '                    getEl("subscribeResult").textContent = "❌ " + (data.message || "Failed to activate");\n';
    html += '                    getEl("subscribeResult").style.color = "#ff4444";\n';
    html += '                }\n';
    html += '            })\n';
    html += '            .catch(function(err) {\n';
    html += '                console.error("Activation error:", err);\n';
    html += '                showToast("❌ Network error", "error");\n';
    html += '            });\n';
    html += '        }\n';
    html += '\n';
    html += '        function showToast(message, type) {\n';
    html += '            type = type || "info";\n';
    html += '            var toast = getEl("toast");\n';
    html += '            var icons = { success: "✅", error: "❌", info: "ℹ️" };\n';
    html += '            toast.className = "toast show " + type;\n';
    html += '            getEl("toastIcon").textContent = icons[type] || "ℹ️";\n';
    html += '            getEl("toastMessage").textContent = message;\n';
    html += '            clearTimeout(toast._timeout);\n';
    html += '            toast._timeout = setTimeout(function() { toast.classList.remove("show"); }, 4000);\n';
    html += '        }\n';
    html += '\n';
    html += '        getEl("phoneInput").addEventListener("keydown", function(e) { if (e.key === "Enter") initiatePayment(); });\n';
    html += '        getEl("voucherInput").addEventListener("keydown", function(e) { if (e.key === "Enter") redeemVoucher(); });\n';
    html += '        getEl("checkPhoneInput").addEventListener("keydown", function(e) { if (e.key === "Enter") checkPlan(); });\n';
    html += '\n';
    html += '        checkSubscriptionStatus();\n';
    html += '\n';
    html += '    })();\n';
    html += '<\/script>\n';
    html += '</body>\n';
    html += '</html>';

    return html;
}
